//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaseFlight.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerTicket
    {
        public int ID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string IDCardOrPassport { get; set; }
        public Nullable<System.DateTime> DateIssueOrExpiry { get; set; }
        public string PlaceIssue { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> PassengerTypeID { get; set; }
    
        public virtual PassengerType PassengerType { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
