//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaseFlight.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaneSeatClass
    {
        public int PlaneID { get; set; }
        public int SeatClassID { get; set; }
        public Nullable<int> Chair { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Plane Plane { get; set; }
        public virtual SeatClass SeatClass { get; set; }
    }
}
