//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaseFlight.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaneAirport
    {
        public int PlaneID { get; set; }
        public int AirportID { get; set; }
        public string DepartureOrArrival { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual Plane Plane { get; set; }
    }
}
