//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaseFlight.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketFlight
    {
        public int TicketID { get; set; }
        public int FlightID { get; set; }
        public string SeatCode { get; set; }
        public Nullable<bool> RoundTrip { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
